version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "react"
      - dependency-name: "react-native"
    open-pull-requests-limit: 0
